name: Build and Compress Docker Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nnynn/slidev
    - name: Save Docker image
      run: docker save nnynn/slidev:latest | xz -z - > slidev.tar.xz
    - name: Upload Compressed Image
      uses: actions/upload-artifact@v4.3.1     
      with:
        name: compressed-docker-image
        path: ./your-image-name.tar.xz
