name: Build and Compress Docker Image
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract version from Python file
      id: extract_version
      run: |
        VERSION=$(grep 'VERSION = ' slidev.py | awk '{print $3}' | tr -d '"')
        echo "Extracted version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nnynn/slidev:$VERSION
    - name: Save Docker image
      run: docker save nnynn/slidev:$VERSION | xz -z -T0 - > slidev.tar.xz
    - name: Upload Compressed Image
      uses: actions/upload-artifact@v4.3.1
      with:
        name: compressed-docker-image
        path: ./slidev.tar.xz
