name: Build and Compress Docker Image
on:
  push:
    tags:
      - '*'
  workflow_dispatch: 
    inputs:
      tag_name:
        description: 'Tag Name (leave blank to use latest)'
        required: false
        default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Determine Tag Name
      id: tag_name
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
        else
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        fi
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nnynn/slidev:$TAG_NAME
    - name: Save Docker image
      run: docker save nnynn/slidev:$TAG_NAME | xz -z -T0 - > slidev.tar.xz
    - name: Upload Compressed Image
      uses: actions/upload-artifact@v4.3.1     
      with:
        name: compressed-docker-image
        path: ./slidev.tar.xz
