name: Build and Compress Docker Image
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract tag name
      id: get_tag
      run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nnynn/slidev:${{ steps.get_tag.outputs.TAG }}
    - name: Save Docker image
      run: docker save nnynn/slidev:${{ steps.get_tag.outputs.TAG }} | xz -z -T0 - > slidev.tar.xz
    - name: Upload Compressed Image
      uses: actions/upload-artifact@v4.3.1     
      with:
        name: compressed-docker-image
        path: ./slidev.tar.xz
